### ISSUE TITLE
Move ROI arduino code to Other/Arduino\ ROI/

### ISSUE THREAD

**Issue by JacksonStillwagon** [UA-NASA-Robotics/2024-2025-Robot-Code#3]
Take the code that is loaded onto the Arduino from the ROI repo into the Other/Arduino\ ROI/ folder in this repo. The idea is that when we need to run the robot, we can look in this repo for everything we need.

**Comment by Mapy542** [comment]
What do you think of the ROI submodule?

**Comment by JacksonStillwagon** [comment]
I 'think' I like it, we'll have to see how it pans out throughout the year. Good work either way!
