### ISSUE TITLE
Get Controller Inputs

### ISSUE THREAD

**Issue by JacksonStillwagon** [UA-NASA-Robotics/2024-2025-Robot-Code#5]
I can all but guarantee that there already exists a ROS node that takes in controller inputs and publishes them to a topic. If someone can find one and make it work with the controllers we have at express that will clear up most of the work for this package. Short of that write something.

**Comment by JacksonStillwagon** [comment]
Try looking into this package
Joystick Package: [Joy](https://wiki.ros.org/joy)

**Comment by eseer-divad** [comment]
https://github.com/UA-NASA-Robotics/2024-2025-Robot-Code/tree/feature/add_controller_inputs/ROS/RS_Package

Started building this out a bit, the README I cut & paste together might be a good resource for other devs.

**Comment by eseer-divad** [comment]
![Screenshot_2024-10-09_03-33-26](https://github.com/user-attachments/assets/127fc509-79ef-4d66-b18b-4666730283f4)

**Comment by eseer-divad** [comment]
i have controller inputs and a nice bash file to run the test for turtlesim, just takes one command

i can make a bash file to run it to publish for actual run (goes to priority node / queue package) 

just need to document my work and I'll have a PR for someone to review, I'm gonna start on priority node concept as soon as I'm done with that fyi

then I will walk back and see about fixing things to the control scheme we want

currently it is just left stick (all 4 directions), and rotations are calculated by teleop_twist_joy
